### ISSUE TITLE
Move dev to single github repo

### ISSUE THREAD

**Issue by davidanthoff** [Mike43110/julia.vscode#8]
Hi @Mike43110,

I've just now saw this repo. I've created a new repo for a julia VS Code extension [here](https://github.com/JuliaEditorSupport/julia-vscode). It is published on the marketplace etc. The next big feature that is almost done is linter support.

Might make sense if you pointed people to that repository and we concentrate all VS Code extension efforts in that one location?

Cheers,
David

**Comment by mikewl** [comment]
Agreed completely. Just edited the readme to point at the your repository.
Should be coding again soon so I am looking forward to testing it out!
